FROM quay.io/maherzubair/sigma-md
RUN git clone https://github.com/Meharking07/hi /root/Meharking07/hi
WORKDIR /root/Meharking07/hi/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
 
